version: '3.8'

services:
  # Laravel Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./storage/logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_URL=${APP_URL:-http://localhost}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TTL=${JWT_TTL:-60}          # Token TTL para sesiones normales (1 hora)
      - JWT_REFRESH_TTL=${JWT_REFRESH_TTL:-20160}  # Refresh Token TTL (14 días)
      - JWT_REMEMBER_TTL=${JWT_REMEMBER_TTL:-43200}  # Token TTL para "remember_me" (30 días)
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT:-8000}:80"

  # Base de datos MySQL
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "${DB_PORT:-3306}:3306"

  # phpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${DB_ROOT_PASSWORD:-root}
    networks:
      - app-network
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
